# Configuration for Super-Resolution to Low-Resolution Forecasting

trainer:
  max_epochs: 30
  batch_size: 2
  num_workers: 2
  checkpoint: null  # Path to checkpoint to resume from, or null
  checkpoint_save_path: "/lustre/orion/csc662/proj-shared/janet/forecasting/orbit_main/era5_forecasting_0.25_deg_baseline"
  data_type: "bfloat16"  # "float32", "bfloat16", "float16"
  train_loss: "lat_mse"  # this field is not used by the training script, loss is hardcoded
  num_gpus: 8
  buffer_size: 50

parallelism:
  fsdp: 1
  simple_ddp: 1
  tensor_par: 1
  seq_par: 1

data:
  # era5_dir: "/lustre/orion/lrn036/world-shared/data/superres/era5/1.40625_deg/"
  era5_dir: "/lustre/orion/lrn036/world-shared/data/superres/era5/0.25_deg/"
  forecast_type: "direct"  # "direct", "iterative", "continuous"
  pred_range: 120  # lead time
  enable_monthly_loader: True
  
  # Input variables
  variables:
    - "temperature"
    # - "geopotential"
    # - "u_component_of_wind"
    - "2m_temperature"
    # - "2m_temperature_max"
    # - "2m_temperature_min"
    - "10m_u_component_of_wind"
    - "10m_v_component_of_wind"
    - "latitude"
    - "land_sea_mask"
    - "orography"
    - "landcover"
  
  # Output variables
  out_variables:
    - "2m_temperature"

  # Variable weights for loss calculation
  var_weights:
    2m_temperature: 1.0
    10m_u_component_of_wind: 1.0
    10m_v_component_of_wind: 1.0

model:
  preset: "res_slimvit"  # Model architecture
  
  # Image dimensions
  img_size: [180, 360]  # Low-resolution input [H, W]
  superres_factor: 4 # Super-resolution factor
  downsample_mode: "bilinear"  # Downsampling mode: "area", "bilinear", "bicubic", "nearest"
  
  # Model architecture
  history: 1  # Number of historical timesteps
  cnn_ratio: 4
  patch_size: 2  
  embed_dim: 256
  depth: 6
  decoder_depth: 4
  num_heads: 4
  mlp_ratio: 4.0
  drop_path: 0.1
  drop_rate: 0.1
  learn_pos_emb: True
  
  # Optimizer settings
  base_lr: 5e-3  # Base learning rate scaled by (num_gpus ** 0.8)
  weight_decay: 0.00001
  beta_1: 0.9
  beta_2: 0.99
  
  # Scheduler settings
  warmup_epochs: 5
  warmup_start_lr: 1e-6
  eta_min: 1e-8
